### ISSUE TITLE
weird use of "boto profile"

### ISSUE THREAD

**Issue by keen99** [cytopia/aws-export-assume-profile#3]
you keep saying "boto profile" - but you mean "profile"  (or aws credentials file profile, perhaps).  

since there's nothing "boto" specific here, it shouldn't be referenced.     none of the sdk docu, none of the awscli docu, refers to this as a "boto" profile.   boto is underlying on some of the aws tooling.   

anyway, had to say something because the readme just feels really weird.

**Comment by danvaida** [comment]
True that. Boto is AWS' Python SDK, so this should not be referenced in this repo as it doesn't have absolutely anything to do with it. Yes, `boto`, `boto3`, `botocore` and others can and do use ENV vars which are the meat of this script, but the use case is not exclusively limited.
